import React from 'react'

import { allNews, allStory, allMustSee, AllOpinion, allPodcast, allFeatured, multipleVideo, allImage } from '../../http'
import { useRouter } from 'next/router'
import Head from 'next/head'
import MainNews from '../../components/news/MainNews'
import SecondNews from '../../components/news/SecondNews'
import ThirdNews from '../../components/news/ThirdNews'
import MustSee from '../../components/mustsee/index'
import Story from '../../components/story'
import { MostViewedImage } from '../../components/featuredImage'
import { Article1, Article2 } from './../../components/FeaturedArticle'
import NewsLetter from './../../components/newsletter'
import Podcaste from './../../components/podcaste'
import Link from 'next/link'
const Cotegory = ({ news, story, mustsee, opinion, podcast, featuredArticle, allvideo, multipleimage}) => {
  const router = useRouter();
  console.log(news, "news")
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href={'/css/style.css'} rel={'stylesheet'} />
        <link href={'/css/custom.css'} rel={'stylesheet'} />
        <link href={'/css/article.css'} rel={'stylesheet'} />
      </Head>
      <div className="section-banner">
        <div className="scrn-container">
          <div className="banner-meun">
            <div className="row">
              <div className="col-xl-12">
                <div className="section-menu-top">
                  <div className="lift-side-text text-capitalize">
                    {router.query.slug}
                  </div>
                  <div className="right-side-text-10">

                  </div>
                </div>
              </div>
            </div>

            <div className="Unock-text-in row">
              <div className="col-xl-12">
                <div className="farme-meun-in-all-9">
                  {
                    news.bool && news.data.length != 0 && news.data.slice(0, 2).map((newsItem, key) => {
                      if (key == 0) {
                        return <MainNews newsItem={newsItem} title={router.query.slug} />
                      } else if (key == 1 || key == 2) {
                        return <SecondNews newsItem={newsItem} title={router.query.slug} />
                      }
                    })
                  }

                </div>
              </div>
              <div className="col-xl-5">
                <div className="right-side-menu">
                  {
                    news.bool && news.data.length != 0 && news.data.slice(2, 500).map((newsItems, key) => {

                      return <ThirdNews newsItems={newsItems} />

                    })
                  }

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>



      <section className="section-banner-in">
        <div className="container">

          <div className="row">
            <div className="col-xl-7 banner-meun">
              <div className=" meun-bar">
                <div className="lift-side-text">Must See</div>
                <div class="right-side-text-10"><Link href={`/mustsee/all`}>See All</Link></div>
              </div>
              <div className="farme-tltle">

                {
                  mustsee.bool && mustsee.data.length != 0 && story.data.slice(0, 3).map((mustItem, key) => {
                    return <MustSee mustItem={mustItem} />
                  })
                }

              </div>
            </div>
            <div className="col-xl-5 ">
              <div className="imgex">
                <img className='mt-0 h-270' src="/images/Rectangle 2496.png" />
              </div>
                <MostViewedImage multipleimage={multipleimage} />

            </div>
          </div>

        </div>
      </section>
      <section class="section-banner-in">
        <div class="scrn-container">
          <div class="section-scrn_banner">
            <div class="row meun-bar-lo">
              <div class="col-xl-12">
                <div class="lift-side_lg">
                  <div class="lift-side-text">
                    Featured Articles
                  </div>
                  <div class="right-side-all_text">
                    <ul class="nav nav-tabs">
                      <li class="nav-item fv-tab-li">
                        <a class="nav-link active fv-tab" data-bs-toggle="tab" href="#home">Home</a>
                      </li>
                      <li class="nav-item fv-tab-li">
                        <a class="nav-link fv-tab" data-bs-toggle="tab" href="#menu1">Menu 1</a>
                      </li>
                      <li class="nav-item fv-tab-li">
                        <a class="nav-link fv-tab" data-bs-toggle="tab" href="#menu2">Menu 2</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="tab-content">
                <div class="tab-pane  fade active show" id="home">
                  home
                  <div class=" row gx-3 ">
                    {
                      featuredArticle.bool && featuredArticle.data.length != 0 && story.data.slice(0, 1).map((curlElem1, key) => {
                        return <div class="col-xl-6"><Article2 articleItem={curlElem1} title={''} /></div>
                      })
                    }

                
                  <div class="col-xl-6">
                    <div className='row '>
                    {
                      featuredArticle.bool && featuredArticle.data.length != 0 && story.data.slice(1, 3).map((curlElem2, key) => {
                        return <div class="col-xl-12 mb-3"><Article1 articleItem={curlElem2} title={''} /></div>
                      })
                    }
                    </div>
                    </div>


                  </div>
                </div>
                {/* <div class="tab-pane  fade" id="menu1">
                  <div class=" row farme_11_go">
                    <div class="col-xl-6">
                      <div class="farme-meun_in_11_box">
                        <div class="farme_meun_in_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_meun_11_text">
                          <div class="farme_meun_conter">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                            <p>Lorem ipsum dolor sit amet, consect tur adipiscing elit, Nulla sed
                              interdum felis, vel imperdiet elit, Suspendisse Lorem ipsum dolor
                              sit interdum felis, vel imperdiet elit Suspendisse Lorem ipsum dolor
                            </p>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-6">
                      <div class="farme-meun_in_11_box">
                        <div class="farme_meun_in_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_meun_11_text">
                          <div class="farme_meun_conter">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                            <p>Lorem ipsum dolor sit amet, consect tur adipiscing elit, Nulla sed
                              interdum felis, vel imperdiet elit, Suspendisse Lorem ipsum dolor
                              sit interdum felis, vel imperdiet elit Suspendisse Lorem ipsum dolor
                            </p>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class=" row farme_meun_toggol_11">
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_in_meun_12">
                          <div class="farme-meun-toggole_12">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_in_meun_12">
                          <div class="farme-meun-toggole_12">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_in_meun_12">
                          <div class="farme-meun-toggole_12">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_in_meun_12">
                          <div class="farme-meun-toggole_12">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tab-pane  fade" id="menu2">
                  <div class=" row farme_11_go">
                    <div class="col-xl-6">
                      <div class="farme-meun_in_11_box">
                        <div class="farme_meun_in_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_meun_11_text">
                          <div class="farme_meun_conter">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                            <p>Lorem ipsum dolor sit amet, consect tur adipiscing elit, Nulla sed
                              interdum felis, vel imperdiet elit, Suspendisse Lorem ipsum dolor
                              sit interdum felis, vel imperdiet elit Suspendisse Lorem ipsum dolor
                            </p>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-6">
                      <div class="farme-meun_in_11_box">
                        <div class="farme_meun_in_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_meun_11_text">
                          <div class="farme_meun_conter">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                            <p>Lorem ipsum dolor sit amet, consect tur adipiscing elit, Nulla sed
                              interdum felis, vel imperdiet elit, Suspendisse Lorem ipsum dolor
                              sit interdum felis, vel imperdiet elit Suspendisse Lorem ipsum dolor
                            </p>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class=" row farme_meun_toggol_11">
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_in_meun_12">
                          <div class="farme-meun-toggole_12">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img" />
                        <img src="images/Rectangle 2500.png" />
                      </div>
                      <div class="farme_in_meun_12">
                        <div class="farme-meun-toggole_12">
                          <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                        </div>
                        <span>December 22, 2022 | Politics</span>
                      </div>
                    </div>
                  </div>
                  <div class="col-xl-3">
                    <div class="farme_meun_text_12">
                      <div class="farme_col_meun-_img">
                        <img src="images/Rectangle 2500.png" />
                      </div>
                      <div class="farme_in_meun_12">
                        <div class="farme-meun-toggole_12">
                          <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                        </div>
                        <span>December 22, 2022 | Politics</span>
                      </div>
                    </div>
                  </div>
                  <div class="col-xl-3">
                    <div class="farme_meun_text_12">
                      <div class="farme_col_meun-_img">
                        <img src="images/Rectangle 2500.png" />
                      </div>
                      <div class="farme_in_meun_12">
                        <div class="farme-meun-toggole_12">
                          <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                        </div>
                        <span>December 22, 2022 | Politics</span>
                      </div>
                    </div>
                  </div>
                </div> */}
              </div>
            </div>

          </div>
        </div>
      </section>
      <section>
        <div className="container">
          <div className="row">
            
            <div className='col-md-7'>
              <NewsLetter />
            </div>
            <div className='col-md-5'>
            <div className="imgex mt-4">
              <img className='h-270' src="/images/Rectangle 2496.png" />
            </div>
            </div>
          </div>
        </div>
      </section>
      <Podcaste podcast={podcast} />
    </>
  )
}

export default Cotegory

export async function getServerSideProps(context) {
  console.log(context.query)
  const { cu, slug } = context.query;
  let json_object = {

  };

  if (cu) {
    json_object['countryslug'] = cu;
  }

  if(slug){
    json_object['categoryslug'] = slug;
  }
  const { data: news } = await allNews(json_object);
  const { data: story } = await allStory(json_object);
  const { data: mustsee } = await allMustSee(json_object);
  const { data: opinion } = await AllOpinion(json_object);
  const { data: podcast } = await allPodcast(json_object);

  const { data: featuredArticle } = await allFeatured(json_object);
  const { data: allvideo } = await multipleVideo(json_object);
  const { data: multipleimage } = await allImage(json_object);
  return {
    props: { news, story, mustsee, featuredArticle, podcast, opinion, allvideo, multipleimage}
  }
}