import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { allContent } from '@/http'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export default function Home({content}) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div>
      <ul>
      {
          content.data.length !=0 && content.data.map((item)=>(
            <li key={item.id}>
            <Link href={item.slug}>
              {item.description}
            </Link>
          </li>
          ))
        }
      </ul>
     </div>
    </>
  )
}

export async function getServerSideProps(context) {
const {data:content} = await allContent();
return { 
  props: { content } 
}
}
