import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { allNews, allStory, allMustSee, AllOpinion, allPodcast, allFeatured, multipleVideo, allImage } from '@/http'
import Link from 'next/link'
import MainNews from '../components/news/MainNews'
import SecondNews from '../components/news/SecondNews'
import ThirdNews from '../components/news/ThirdNews'
import MustSee from '../components/mustsee/index'
import Story from '../components/story'
import FeaturedVideo from '../components/featuredVideo'
import MoreLikeVideo from '../components/featuredVideo/MoreLikeVideo'
import { Article1, Article2 } from '../components/FeaturedArticle'
import { useState } from 'react'
import OpinionComponent from '../components/opinion'
import { FeaturedImage, LikeImage } from '../components/featuredImage'
import Podcaste from '../components/podcaste'
import NewsLetter from './../components/newsletter'
const inter = Inter({ subsets: ['latin'] })

export default function Home({ news, story, mustsee, opinion, podcast, featuredArticle, allvideo, multipleimage }) {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href={'./css/style.css'} rel={'stylesheet'} />
        <link href={'/css/custom.css'} rel={'stylesheet'} />
      </Head>
      <div class="section-banner">
        <div class="scrn-container">
          <div class="banner-meun">
            <div class="row">
              <div class="col-xl-12">
                <div class="section-menu-top">
                  <div class="lift-side-text">
                    Latest News
                  </div>
                  <div class="right-side-text-10">
                  <Link href={`/news/all`}>See All</Link>
                  </div>
                </div>
              </div>
            </div>

            <div class="Unock-text-in row">
              <div class="col-xl-7">
                <div class="farme-meun-in-all-9">
                  {
                    news.bool && news.data.length != 0 && news.data.slice(0, 3).map((newsItem, key) => {
                      if (key == 0) {
                        return <MainNews newsItem={newsItem} title={''} />
                      } else if (key == 1 || key == 2) {
                        return <SecondNews newsItem={newsItem} title={''} />
                      }
                    })
                  }

                </div>
              </div>
              <div class="col-xl-5">
                <div class="right-side-menu row">

                  {
                    news.bool && news.data.length != 0 && news.data.slice(3, 7).map((newsItems, key) => {

                      return <ThirdNews newsItems={newsItems} title={''} />

                    })
                  }

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


      {/* mustsee section */}
      <section class="section-banner-in mustSee">
        <div class="scrn-container">
          <div class="banner-menu-bg">
            <div class="row">
              <div class="col-xl-7">
                <div class="meun-bar">
                  <div class="lift-side-text">Must See</div>
                  <div class="right-side-text-10"><Link href={`/mustsee/all`}>See All</Link></div>
                </div>
                <div class="farme-tltle">
                  {
                    mustsee.bool && mustsee.data.length != 0 && story.data.slice(0, 3).map((mustItem, key) => {
                      return <MustSee mustItem={mustItem} title={mustItem.seo_title} />
                    })
                  }
                </div>
              </div>
              <div class="col-xl-5">
                <div class="farme-meun-right-tilte">
                  <div class="meun-bar">
                    <div class="lift-side-text">To Stories</div>
                    <div class="right-side-text-10"><Link href={`/story/all`}>See All</Link></div>
                  </div>
                  <div class="farme-meun10">
                    {
                      story.bool && story.data.length != 0 && story.data.slice(0, 2).map((storyItem, key) => {
                        return <Story storyItem={storyItem} title={storyItem.seo_title} />
                      })
                    }

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>



      <section>
        <div className="container">
          <div className="row">
            <div className="imgex">
              <img src="images/Rectangle 2496.png" />
            </div>
          </div>
        </div>
      </section>

      <section class="section-banner-box featuredVideo">
        <div class="scrn-container">

          <div class="row top-minu">
            <div class="col-xl-6">
              <div class="section-menu-top  farme-meun-line">
                <div class="lift-side-text">
                  Featured Video
                </div>
                <div class="right-side-text-10">
                <Link href={`video/all`}>See All</Link>
                </div>
              </div>

              {
                allvideo.bool && allvideo.data.length != 0 && story.data.slice(0, 1).map((videoItem, key) => {
                  return <FeaturedVideo videoItem={videoItem} title={''} />
                })
              }

            </div>
            <div class="col-xl-6">
              <div class="right-side-0_bg farme-meun-line">
                <div class="more-in">More Like These</div>
              </div>
              <div class="farme-meun_32">

                {
                  allvideo.bool && allvideo.data.length != 0 && story.data.slice(1, 4).map((videoItem, key) => {
                    return <MoreLikeVideo videoItem={videoItem} title={''} />
                  })
                }
              </div>
            </div>
          </div>
        </div>

      </section>

      <section class="section-banner-in">
        <div class="scrn-container">
          <div class="section-scrn_banner">
            <div class="row meun-bar-lo">
              <div class="col-xl-12">
                <div class="lift-side_lg">
                  <div class="lift-side-text">
                    Featured Articles
                  </div>
                  <div class="right-side-all_text">
                    <ul class="nav nav-tabs">
                      <li class="nav-item fv-tab-li">
                        <a class="nav-link active fv-tab" data-bs-toggle="tab" href="#home">Home</a>
                      </li>
                      <li class="nav-item fv-tab-li">
                        <a class="nav-link fv-tab" data-bs-toggle="tab" href="#menu1">Menu 1</a>
                      </li>
                      <li class="nav-item fv-tab-li">
                        <a class="nav-link fv-tab" data-bs-toggle="tab" href="#menu2">Menu 2</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="tab-content">
                <div class="tab-pane  fade active show" id="home">
                  home
                  <div class=" row farme_11_go align-items-baseline">
                    {
                      featuredArticle.bool && featuredArticle.data.length != 0 && featuredArticle.data.slice(0, 2).map((curlElem1, key) => {
                        return  <div class="col-xl-6"><Article1 articleItem={curlElem1} title={''} /></div>
                      })
                    }

                  </div>
                  <div class=" row farme_meun_toggol_11">
                    {
                      featuredArticle.bool && featuredArticle.data.length != 0 && featuredArticle.data.slice(3, 7).map((curlElem2, key) => {
                        return <div class="col-xl-3"><Article2 articleItem={curlElem2} title={''} /></div>
                      })
                    }

                  </div>
                </div>
                {/* <div class="tab-pane  fade" id="menu1">
                  <div class=" row farme_11_go">
                    <div class="col-xl-6">
                      <div class="farme-meun_in_11_box">
                        <div class="farme_meun_in_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_meun_11_text">
                          <div class="farme_meun_conter">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                            <p>Lorem ipsum dolor sit amet, consect tur adipiscing elit, Nulla sed
                              interdum felis, vel imperdiet elit, Suspendisse Lorem ipsum dolor
                              sit interdum felis, vel imperdiet elit Suspendisse Lorem ipsum dolor
                            </p>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-6">
                      <div class="farme-meun_in_11_box">
                        <div class="farme_meun_in_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_meun_11_text">
                          <div class="farme_meun_conter">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                            <p>Lorem ipsum dolor sit amet, consect tur adipiscing elit, Nulla sed
                              interdum felis, vel imperdiet elit, Suspendisse Lorem ipsum dolor
                              sit interdum felis, vel imperdiet elit Suspendisse Lorem ipsum dolor
                            </p>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class=" row farme_meun_toggol_11">
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_in_meun_12">
                          <div class="farme-meun-toggole_12">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_in_meun_12">
                          <div class="farme-meun-toggole_12">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_in_meun_12">
                          <div class="farme-meun-toggole_12">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_in_meun_12">
                          <div class="farme-meun-toggole_12">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tab-pane  fade" id="menu2">
                  <div class=" row farme_11_go">
                    <div class="col-xl-6">
                      <div class="farme-meun_in_11_box">
                        <div class="farme_meun_in_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_meun_11_text">
                          <div class="farme_meun_conter">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                            <p>Lorem ipsum dolor sit amet, consect tur adipiscing elit, Nulla sed
                              interdum felis, vel imperdiet elit, Suspendisse Lorem ipsum dolor
                              sit interdum felis, vel imperdiet elit Suspendisse Lorem ipsum dolor
                            </p>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-6">
                      <div class="farme-meun_in_11_box">
                        <div class="farme_meun_in_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_meun_11_text">
                          <div class="farme_meun_conter">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                            <p>Lorem ipsum dolor sit amet, consect tur adipiscing elit, Nulla sed
                              interdum felis, vel imperdiet elit, Suspendisse Lorem ipsum dolor
                              sit interdum felis, vel imperdiet elit Suspendisse Lorem ipsum dolor
                            </p>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class=" row farme_meun_toggol_11">
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img">
                          <img src="images/Rectangle 2500.png" />
                        </div>
                        <div class="farme_in_meun_12">
                          <div class="farme-meun-toggole_12">
                            <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                          </div>
                          <span>December 22, 2022 | Politics</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-3">
                      <div class="farme_meun_text_12">
                        <div class="farme_col_meun-_img" />
                        <img src="images/Rectangle 2500.png" />
                      </div>
                      <div class="farme_in_meun_12">
                        <div class="farme-meun-toggole_12">
                          <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                        </div>
                        <span>December 22, 2022 | Politics</span>
                      </div>
                    </div>
                  </div>
                  <div class="col-xl-3">
                    <div class="farme_meun_text_12">
                      <div class="farme_col_meun-_img">
                        <img src="images/Rectangle 2500.png" />
                      </div>
                      <div class="farme_in_meun_12">
                        <div class="farme-meun-toggole_12">
                          <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                        </div>
                        <span>December 22, 2022 | Politics</span>
                      </div>
                    </div>
                  </div>
                  <div class="col-xl-3">
                    <div class="farme_meun_text_12">
                      <div class="farme_col_meun-_img">
                        <img src="images/Rectangle 2500.png" />
                      </div>
                      <div class="farme_in_meun_12">
                        <div class="farme-meun-toggole_12">
                          <h1>Sir Gavin Williamson reesigns after bullying claims</h1>
                        </div>
                        <span>December 22, 2022 | Politics</span>
                      </div>
                    </div>
                  </div>
                </div> */}
              </div>
            </div>

          </div>
        </div>
      </section>

      <section class="section-banner-in">
        <div class="scrn-container">
          <div class="row farme-meun_scen">
            <div class="col-lg-6">
              <div class="card-fluid-1 section-scrn_banner">
                <div class="title-box lift-side_lg">
                  <div class="lift-side-text">
                    Opinion
                  </div>
                  <div class="right-side-text">
                  <Link href={`/opinion/all`}>See All</Link>
                  </div>
                </div>

                {
                  opinion.bool && opinion.data.length != 0 && opinion.data.slice(0, 2).map((opinionItem, key) => {
                    return <OpinionComponent opinionItem={opinionItem} title={''} />
                  })
                }


              </div>
            </div>
            <div class="col-lg-6">
              <NewsLetter podcast={podcast} />
            </div>
          </div>
        </div>
      </section>

      <section class="section-banner-box featuredVideo">
        <div class="scrn-container">

          <div class="row top-minu">
            <div class="col-xl-6">
              <div class="section-menu-top  farme-meun-line">
                <div class="lift-side-text">
                  Featured Images
                </div>
                <div class="right-side-text-10">
                  <Link href={`/image/all`}>See All</Link>
                </div>
              </div>

              {
                multipleimage.bool && multipleimage.data.length != 0 && multipleimage.data.slice(0, 1).map((imageItem1, key) => {
                  return <FeaturedImage imageItem1={imageItem1} title={''} />
                })
              }

            </div>
            <div class="col-xl-6">
              <div class="right-side-0_bg farme-meun-line">
                <div class="more-in">More Like These</div>
              </div>
              <div class="farme-meun_32">

                {
                  multipleimage.bool && multipleimage.data.length != 0 && multipleimage.data.slice(1, 4).map((imageItem2, key) => {
                    return <LikeImage imageItem2={imageItem2} title={''} />
                  })
                }
              </div>
            </div>
          </div>
        </div>

      </section>
      {/* <section class="section-banner-box">
        <div class="scrn-container">
          <div class="row  top-minu">
            <div class="col-xl-6">
              <div class="section-menu-top  farme-meun-line">
                <div class="lift-side-text">
                  Featured Images
                </div>
                <div class="right-side-text-10">
                  See All
                </div>
              </div>
              <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner ">
               
                
                </div>
                <button class="carousel-control-prev fratured-control" type="button" data-bs-target="#carouselExampleControls"
                  data-bs-slide="prev">
                  <img src="images/prev.png" />
                </button>
                <button class="carousel-control-next fratured-control" type="button" data-bs-target="#carouselExampleControls"
                  data-bs-slide="next">
                  <img src="images/next.png" />
                </button>
              </div>
            </div>
            <div class="col-xl-6">
              <div id="f-image" class="carousel slide" data-bs-ride="carousel">
                <div class="right-side-0_bg farme-meun-line f-image-top-box">
                  <div class="more-in">More Like These</div>
                  <div class="f-image-con-box">
                    <button class="carousel-control-prev f-imag-con f-imag-con-prev" type="button" data-bs-target="#f-image" data-bs-slide="prev">
                      <img src="images/prev.png" />
                    </button>
                    <button class="carousel-control-next f-imag-con f-imag-con-next" type="button" data-bs-target="#f-image" data-bs-slide="next">
                      <img src="images/next.png" />
                    </button>
                  </div>
                </div>

                <div class="carousel-inner">
                  <div class="carousel-inner">
                  {
                    multipleimage.bool && multipleimage.data.length != 0 && multipleimage.data.slice(1, 2).map((imageItem, key) => {
                      return <LikeImage imageItem={imageItem} title={''} />
                    })
                  }
                   
                  </div>
                </div>

              </div>



            </div>
          </div>

        </div>
      </section> */}

      <section class="section-banner-in-0">
        <div class="scrn-container">
          <div class="row">
            <div class=" col-xl-12 imgex">
              <img src="images/Rectangle 2496.png" />
            </div>
          </div>
        </div>
      </section>

    <Podcaste podcast={podcast}  />

      <section class="section-banner-in-0">
        <div class="scrn-container">
          <div class="row">
            <div class="col-xl-12 ">
              <NewsLetter />
            </div>
          </div>

        </div>
      </section>
    </>
  )
}

export async function getServerSideProps(context) {
  const { cu, cot } = context.query;

  let data = {};

  if (cu) {
    data['slug'] = cu;
  }

  const { data: news } = await allNews(Object.keys(data).length != 0 ? data : null);
  const { data: story } = await allStory();
  const { data: mustsee } = await allMustSee();
  const { data: opinion } = await AllOpinion();
  const { data: podcast } = await allPodcast();
  const { data: featuredArticle } = await allFeatured();
  const { data: allvideo } = await multipleVideo();
  const { data: multipleimage } = await allImage();

  return {
    props: { news, story, mustsee, featuredArticle, podcast, opinion, allvideo, multipleimage }
  }
}
