import React from 'react'
import { singleNews,allNews,allStory  } from '../../http'
import SingleNews from '../../components/news/SingleNews'
import Head from 'next/head'
const NewsArticle = ({ data,lable,story=''}) => {
  return (
    <>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href={'/css/style.css'} rel={'stylesheet'} />
        <link href={'/css/custom.css'} rel={'stylesheet'} />
        <link href={'/css/article.css'} rel={'stylesheet'} />
      </Head>
    {lable === 'single'?<SingleNews data={data.data} story={story} />:'all'}
    </>
  )
}

export default NewsArticle

export async function getServerSideProps(context) {

  const { id,slug } = context.query;
  let object = {

  };

  if (id) {
    object['id'] = id;
  }

  let lable = 'single'

if(slug === 'all'){
  lable = 'all';
}
  if(lable === 'single'){
    const { data } = await singleNews(object);
    const { data: story } = await allStory();
    return {
      props: { data,lable,story }
    }
  }else{
    const { data } = await allNews();

    return {
      props: { data,lable }
    }
  }

}